version: '3.8'

services:
  strapi:
    image: '${CI_REGISTRY_IMAGE}/strapi'
    env_file:
      - ./strapi/.env
      - ./web/.env
    environment:
      DB_HOST: postgres
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      STRAPI_HOST: '0.0.0.0'
      STRAPI_PORT: '1337'
      STRAPI_APP_KEYS: ${STRAPI_APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      JWT_SECRET: ${JWT_SECRET}
      NEXT_PUBLIC_STRAPI_URL: ${NEXT_PUBLIC_STRAPI_URL}
    volumes:
      - /srv/nollning/strapi:/srv/app
    networks:
      - traefik
      - nollning
    restart: always
    labels:
      - 'traefik.http.routers.strapi.rule=Host(`${NEXT_PUBLIC_STRAPI_URL}`)'
