version: '3.8'
networks:
  traefik:
    external: true
  nollning:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: e_nollning
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - /srv/nollning/postgres/:/var/lib/postgresql/data
    networks:
      - nollning
      - traefik
