version: '3.8'
networks:
  traefik:
    external: true
  nollning:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./postgres/:/var/lib/postgresql/data
    networks:
      - nollning
      - traefik
