version: '3.8'
networks:
  traefik:
    external: true
  nollning:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-e_nollning}
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - ./postgres/:/var/lib/postgresql/data
    networks:
      - nollning
      - traefik
