version: '3.8'
networks:
  traefik:
    external: true

services:
  strapi:
    image: '${IMAGE_NAME}-strapi'
    environment:
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      STRAPI_HOST: '0.0.0.0'
      STRAPI_PORT: '1337'
      STRAPI_APP_KEYS: ${STRAPI_APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      JWT_SECRET: ${JWT_SECRET}
      STRAPI_URL: ${STRAPI_URL}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      WIKI_URL: ${WIKI_URL}
      WIKI_USERNAME: ${WIKI_USERNAME}
      WIKI_PASSWORD: ${WIKI_PASSWORD}
      NODE_ENV: production
    networks:
      - traefik
      - default
    restart: unless-stopped
    volumes:
      - /srv/nollning/uploads:/app/public/uploads
    labels:
      - 'traefik.http.routers.$COMPOSE_PROJECT_NAME-strapi.rule=Host(`admin.$DEPLOY_URL`)'

  web:
    image: '${IMAGE_NAME}-web'
    environment:
      STRAPI_URL: ${STRAPI_URL}
      STRAPI_API_TOKEN: ${STRAPI_API_TOKEN}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      EBREV_URL: ${EBREV_URL}
      EBREV_API_KEY: ${EBREV_API_KEY}
      NODE_ENV: production
    networks:
      - traefik
      - default
    restart: unless-stopped
    labels:
      - 'traefik.http.routers.$COMPOSE_PROJECT_NAME-web.rule=HostRegexp(`$DEPLOY_URL`, `{subdomain:[\d]{4}}.$DEPLOY_URL`)'
