version: '3.8'

services:
  strapi:
    image: "${CI_REGISTRY_IMAGE}/strapi"
    env_file:
      - ./strapi/.env
    environment:
      DB_HOST: postgres
    volumes:
      - ./strapi:/srv/strapi
    networks:
      - traefik
      - nollning
    restart: always
    labels:
      - "traefik.http.routers.strapi.rule=Host(`admin.nollning.esek.se`)"
