version: '3.8'
networks:
  nollning:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-e_nollning}
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - ./srv/postgres/:/var/lib/postgresql/data
    networks:
      - nollning

  pg_admin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: macapar@esek.se
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - '5050:80'
    networks:
      - nollning
