version: '3.8'
networks:
  traefik:
    external: true

services:
  strapi:
    image: '${CI_REGISTRY_IMAGE}/strapi'
    environment:
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      STRAPI_HOST: '0.0.0.0'
      STRAPI_PORT: '1337'
      STRAPI_APP_KEYS: ${STRAPI_APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      JWT_SECRET: ${JWT_SECRET}
      STRAPI_URL: ${STRAPI_URL}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      WIKI_URL: ${WIKI_URL}
      WIKI_USERNAME: ${WIKI_USERNAME}
      WIKI_PASSWORD: ${WIKI_PASSWORD}
      NODE_ENV: production
    networks:
      - traefik
    restart: always
    volumes:
      - /srv/nollning/uploads:/app/public/uploads
    labels:
      - 'traefik.http.routers.strapi.rule=Host(`admin.nollning.esek.se`)'

  web:
    image: '${CI_REGISTRY_IMAGE}/web'
    environment:
      STRAPI_URL: ${STRAPI_URL}
      STRAPI_API_TOKEN: ${STRAPI_API_TOKEN}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      EBREV_URL: ${EBREV_URL}
      EBREV_API_KEY: ${EBREV_API_KEY}
      NODE_ENV: production
    networks:
      - traefik
    restart: always
    labels:
      - 'traefik.http.routers.nollning-web.rule=HostRegexp(`nollning.esek.se`, `{subdomain:[\d]{4}}.nollning.esek.se`)'
