version: '3.8'
networks:
  traefik:
    external: true
  nollning:
    driver: bridge

services:
  strapi:
    image: '${CI_REGISTRY_IMAGE}/strapi'
    environment:
      DB_HOST: postgres
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      STRAPI_HOST: '0.0.0.0'
      STRAPI_PORT: '1337'
      STRAPI_APP_KEYS: ${STRAPI_APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - traefik
      - nollning
    restart: always
    labels:
      - 'traefik.http.routers.strapi.rule=Host(`nollning.esek.se`) && PathPrefix(`/content`)'
      - 'traefik.http.routers.strapi.middlewares=strip-content@file'

  postgres:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    volumes:
      - /srv/nollning/postgres:/var/lib/postgresql/data
    networks:
      - nollning
      - traefik
